// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shifter.Model;

namespace Shifter.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shifter.Model.AccessRight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Access")
                        .IsRequired();

                    b.Property<int?>("AccessRightsGroupId");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AccessRightsGroupId");

                    b.ToTable("AccessRights");
                });

            modelBuilder.Entity("Shifter.Model.AccessRightsGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("AccessRightsGroup");
                });

            modelBuilder.Entity("Shifter.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessRightsGroupId");

                    b.Property<string>("EmailAddress")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("PasswordHash")
                        .IsRequired();

                    b.Property<string>("PasswordSatl")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AccessRightsGroupId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shifter.Model.Workshift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TemplateId");

                    b.HasKey("Id");

                    b.ToTable("Workshift");
                });

            modelBuilder.Entity("Shifter.Model.WorkshiftPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DurationMinutes");

                    b.Property<DateTime>("StartTime");

                    b.Property<int>("TemplateId");

                    b.Property<int?>("WorkshiftTemplateId");

                    b.HasKey("Id");

                    b.HasIndex("WorkshiftTemplateId");

                    b.ToTable("WorkshiftPart");
                });

            modelBuilder.Entity("Shifter.Model.WorkshiftPartTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DefaultDurationMinutes");

                    b.Property<DateTime>("DefaultStartTime");

                    b.Property<string>("Description");

                    b.Property<bool>("IsWork");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("WorkshiftPartTemplate");
                });

            modelBuilder.Entity("Shifter.Model.WorkshiftTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("WorkshiftTemplate");
                });

            modelBuilder.Entity("Shifter.Model.AccessRight", b =>
                {
                    b.HasOne("Shifter.Model.AccessRightsGroup")
                        .WithMany("AccessRights")
                        .HasForeignKey("AccessRightsGroupId");
                });

            modelBuilder.Entity("Shifter.Model.User", b =>
                {
                    b.HasOne("Shifter.Model.AccessRightsGroup", "AccessRightsGroup")
                        .WithMany()
                        .HasForeignKey("AccessRightsGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Shifter.Model.WorkshiftPart", b =>
                {
                    b.HasOne("Shifter.Model.WorkshiftTemplate")
                        .WithMany("WorkshiftParts")
                        .HasForeignKey("WorkshiftTemplateId");
                });
#pragma warning restore 612, 618
        }
    }
}
